language: csharp

install:
  - sudo apt-get install -y libglib2.0-cil-dev libgtk2.0-cil-dev libglade2.0-cil-dev
  - sudo apt-get install -y liblog4net-cil-dev

mono:
  - latest
  - 3.12.0

script:    # build console application and gtk gui
  - ./build-linux/build-lnx-themonospot.sh
  - ./build-linux/build-lnx-themonospot-gtk.sh
